name: Build_Release
on:
  # See the documentation for more intricate event dispatch here:
  # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
  push:
    branches:
    - "master"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Docker Image and Extract Build Artifacts
      run: ./build-in-docker.sh
    - uses: "marvinpinto/action-automatic-releases@latest"
      with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "Dev Build"
        automatic_release_tag: "latest"
        files: out/*
    - name: Build and Push Docker Image
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository_owner }}/ipfs-crawler
        github_token: ${{ secrets.GITHUB_TOKEN }}
