ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

# Golint rules
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]

# Extra rules
[rule.unnecessary-stmt]
[rule.modifies-value-receiver]
[rule.constant-logical-expr]
[rule.range-val-in-closure]
[rule.waitgroup-by-value]
[rule.bare-return]
[rule.unused-receiver]
[rule.unhandled-error]
arguments =["fmt.Printf", "fmt.Println"]
[rule.string-of-int]
[rule.useless-break]